application: rfpow301
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /datastore/.*
  script: datastore.datatest.app

- url: /.*
  script: test.app


libraries:
- name: jinja2
  version: "2.6"
- name: lxml
  version: "2.3"
