application: rfpow301
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
 - appstats: on

handlers:
- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /datastore/.*
  script: datatest.app

- url: .*
  script: main.app


libraries:
- name: jinja2
  version: "2.6"
- name: lxml
  version: "2.3"
