application: rfpowjohn2
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
 - appstats: on

handlers:
- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /cron/merx
  login: admin
  script: main.app

- url: /cron/rfpdotca
  login: admin
  script: main.app

- url: /cron/satender
  login: admin
  script: main.app

- url: /cron/email
  login: admin
  script: main.app
  
- url: /test.*
  login: admin
  script: gaeunit.application

- url: .*
  script: main.app

  
libraries:
- name: jinja2
  version: "2.6"
- name: lxml
  version: "2.3"
